/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guessnum;
import java.util.Random;
import java.util.Scanner;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author User
 */
public class Game extends javax.swing.JFrame {

    /**
     * Creates new form Game
     */
    public Game() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        tname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        guess = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        pic = new javax.swing.JLabel();
        tsc = new javax.swing.JLabel();
        rd = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1473, 0, -1, 624));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(242, 242, 242));
        jLabel2.setText("Guess the number!!!");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 490, 160));

        name.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        name.setForeground(new java.awt.Color(242, 242, 242));
        name.setText("Name");
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 90, 30));

        tname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tnameKeyReleased(evt);
            }
        });
        getContentPane().add(tname, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 299, 43));

        jLabel4.setFont(new java.awt.Font("SimSun", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Attempts allowed is 3");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 162, -1));

        guess.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        guess.setText("Play");
        guess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guessActionPerformed(evt);
            }
        });
        getContentPane().add(guess, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 146, -1));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 566, 146, 41));

        pic.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 48)); // NOI18N
        pic.setForeground(new java.awt.Color(242, 242, 242));
        getContentPane().add(pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 350, 344, 69));

        tsc.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 48)); // NOI18N
        tsc.setForeground(new java.awt.Color(242, 242, 242));
        getContentPane().add(tsc, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 520, 301, 69));

        rd.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 48)); // NOI18N
        rd.setForeground(new java.awt.Color(242, 242, 242));
        getContentPane().add(rd, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 140, 720, 110));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guessnum/pexels-lucie-liz-3165335.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -4, 1670, 880));

        pack();
    }// </editor-fold>                        

    private void guessActionPerformed(java.awt.event.ActionEvent evt) {                                      
       
        String pname = tname.getText();
        if(tname.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "ENTER YOUR NAME TO PROCEED");
        }
        else
        {
        Random random = new Random();
        int no=0,num=0;
        int count=0,score=0;
        num=random.nextInt(100);
        while(count<3)
        {
            String response=JOptionPane.showInputDialog(null, "Enter your guess between 1 and 100");
            int g=Integer.parseInt(response);
            if(g==num)
            {
                JOptionPane.showMessageDialog(null, "YOUR GUESS IS CORRECT");
                score=score+100;
            }
            else if(g<num)
            {
                JOptionPane.showMessageDialog(null, "YOUR GUESS IS LOW");
            }
            else if(g>num)
            {
                JOptionPane.showMessageDialog(null, "YOUR GUESS IS HIGH");
            }
            else
            {
                System.out.println("INVALID INPUT");
            }
            
            count=count+1;
            pic.setText("Attempt Over:"+count+"");
            tsc.setText("Your score :"+score+"");
        }
         rd.setText("Random number generated is "+num+"");
        }
       
    }                                     

    private void tnameKeyReleased(java.awt.event.KeyEvent evt) {                                  
        // TODO add your handling code here:
        
        
            
            
           
    }                                 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton guess;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel name;
    private javax.swing.JLabel pic;
    private javax.swing.JLabel rd;
    private javax.swing.JTextField tname;
    private javax.swing.JLabel tsc;
    // End of variables declaration                   
}
